### ISSUE TITLE
Remove material icons

### ISSUE THREAD

**Issue by deandreamatias** [pedrolemoz/unicons-flutter#2]
In [pubspec.yaml](https://github.com/pedrolemoz/unicons-flutter/blob/72e3e9575a0fd832d1e105d68cf53f345dde5606/pubspec.yaml#L19), you can remove the line:

uses-material-design: true

Because this package don't use material icons and avoids conflicts with apps that use unicons but not material icons

**Comment by pedrolemoz** [comment]
Thanks for the suggestion. This issue has been fixed [here](https://github.com/pedrolemoz/unicons-flutter/commit/2105d1a3e68bd95dbc98d3bbd9637673d60dfa46)!
